import Head from 'next/head';
import Homepage from './Homepage';
import About from './About';
import Work from './Work';
import Team from './Team';
import Sidebar from '../components/Sidebar';
import Footer from './Footer';

export default function Home() {
  return (
    <div className="container mx-auto lg:px-2 scroll-smooth ">
      <Head>
        <title>Nature</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-smooth">
        <Sidebar />
        <Homepage />
        <About />
        <Work />
        <Team />
        <Footer />
      </div>
    </div>
  );
}
